name:    jamessully-com-au
version: "0.0.0"

dependencies:
- base
- yesod-core
- wai-cors
- wai
- warp
- text

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  jamessully-com-au:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -W
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jamessully-com-au
